package com.android.calculator.security

/**
 * Generated certificate information for tamper detection
 * This file is auto-generated by the build process
 */
object CertificateInfo {
    // Debug certificate fingerprints (SHA-256)
    val DEBUG_CERT_FINGERPRINTS = setOf(
        "SHA256: 3C:01:73:63:03:9B:FB:9F:89:3E:26:63:EA:73:91:C3:4C:E1:04:CE:C9:65:A7:C5:CD:56:61:B6:5C:06:A8:62",
        "SHA256: 3C:01:73:63:03:9B:FB:9F:89:3E:26:63:EA:73:91:C3:4C:E1:04:CE:C9:65:A7:C5:CD:56:61:B6:5C:06:A8:62"
    )
    
    // Release certificate fingerprints (SHA-256) - to be configured for production
    val RELEASE_CERT_FINGERPRINTS = setOf(
        "TODO: Add production certificate fingerprint here"
    )
    
    // Expected APK checksums (SHA-256) - to be populated at build time
    val EXPECTED_APK_CHECKSUMS = setOf(
        "TODO: Add APK checksum here"
    )
    
    // Expected DEX checksums (SHA-256) - to be populated at build time  
    val EXPECTED_DEX_CHECKSUMS = setOf(
        "TODO: Add DEX checksum here"
    )
}
